

import '../styles/globals.css';
import "@rainbow-me/rainbowkit/styles.css";
import Head from 'next/head';
import type { AppProps } from 'next/app';

import { 
  WagmiConfig,
  createClient,
  configureChains   
} from "wagmi";
import { 
  localhost,
  avalancheFuji 
} from "wagmi/chains";
import {
  getDefaultWallets,
  RainbowKitProvider
} from "@rainbow-me/rainbowkit";
import { publicProvider } from "wagmi/providers/public";

const { provider, chains } = configureChains(
  [avalancheFuji, localhost],
  [publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "nexalink",
  chains
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
          <Head>
            <title>NexaLink</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;